from __future__ import annotations
import subprocess
import shutil
import os
import time
from typing import Callable

from .config import cfg
from .platform import is_nixos

# Lokinet config dosyaları (dağıtıma göre sırayla denetlenir)
_CONFIG_PATHS = [
    "/etc/loki/lokinet.ini",
    "/var/lib/lokinet/lokinet.ini",
    "/etc/lokinet/lokinet.ini",
]
_BAK_SUFFIX    = ".entropy-shield.bak"
_MARKER_BEGIN  = "# --- entropy-shield-lokinet-begin ---"
_MARKER_END    = "# --- entropy-shield-lokinet-end ---"

# Lokinet'in dahili DNS resolver adresi (değişmez)
LOKINET_DNS    = "127.3.2.1"
LOKINET_DNS_PORT = 53


class LokinetManager:
    def __init__(self, log: Callable[[str], None]):
        self._log = log
        self._config: str | None = None
        self._was_active: bool   = False
        self._cfg_injected: bool = False

    # ── public API ────────────────────────────────────────────

    def is_installed(self) -> bool:
        return bool(shutil.which("lokinet"))

    def configure(self) -> None:
        """
        Lokinet config dosyasına exit node / SOCKS / DNS ayarlarını yazar.
        NixOS'ta dosya yönetimi NixOS modülüne bırakılır.
        """
        self._log("[LOKINET] Configuring lokinet...")
        self._was_active = self._service_active("lokinet")

        if is_nixos():
            self._log(
                "[LOKINET] NixOS detected — lokinet config is managed by the "
                "NixOS module. Skipping config file modification."
            )
            return

        self._config = self._find_config()

        exit_node  = cfg().get("lokinet", "exit_node").strip()
        socks_port = cfg().get("lokinet", "socks_port")
        use_exit   = cfg().get("lokinet", "use_exit") and bool(exit_node)

        block_lines = [
            _MARKER_BEGIN,
            f"[network]",
            f"keyfile=/var/lib/lokinet/network.private",
        ]

        if use_exit:
            block_lines.append(f"exit-node={exit_node}")
            block_lines.append("exit=true")
        else:
            block_lines.append("exit=false")

        if socks_port:
            block_lines += [
                f"[api]",
                f"enabled=true",
                f"bind=127.0.0.1:{socks_port}",
            ]

        block_lines.append(_MARKER_END)
        block = "\n".join(block_lines) + "\n"

        bak = self._config + _BAK_SUFFIX
        if not os.path.exists(bak):
            shutil.copy2(self._config, bak)

        with open(self._config, "r") as f:
            content = f.read()

        # Varsa eski bloğu kaldır
        content = self._strip_block(content)

        with open(self._config, "w") as f:
            f.write(content)
            f.write("\n" + block)

        self._cfg_injected = True
        self._log(
            f"[LOKINET] Config updated."
            + (f" Exit node: {exit_node}" if use_exit else " (relay mode)")
        )

    def start(self) -> None:
        self._log("[LOKINET] Starting lokinet service...")
        r = subprocess.run(
            ["systemctl", "restart", "lokinet"],
            capture_output=True, text=True,
        )
        if r.returncode != 0:
            raise RuntimeError(f"Failed to start lokinet: {r.stderr.strip()}")
        self._wait_active("lokinet", timeout=20)
        self._log(
            f"[LOKINET] lokinet active. "
            f"DNS resolver: {LOKINET_DNS}:{LOKINET_DNS_PORT}  "
            f"SOCKS: 127.0.0.1:{cfg().get('lokinet', 'socks_port')}"
        )

    def stop(self) -> None:
        self._log("[LOKINET] Stopping lokinet...")
        subprocess.run(["systemctl", "stop", "lokinet"], capture_output=True)

        if not is_nixos() and self._config and self._cfg_injected:
            bak = self._config + _BAK_SUFFIX
            if os.path.exists(bak):
                shutil.copy2(bak, self._config)
                os.unlink(bak)
            self._cfg_injected = False

        if self._was_active:
            subprocess.run(["systemctl", "start", "lokinet"], capture_output=True)

        self._log("[LOKINET] lokinet stopped.")

    # ── NixOS DNS yönlendirme ─────────────────────────────────

    def nixos_redirect_dns(self) -> None:
        """Sistem DNS'ini Lokinet'in dahili resolver'ına yönlendir."""
        dns_addr = f"{LOKINET_DNS}"
        self._log(f"[LOKINET] Redirecting system DNS → {dns_addr}")
        self._do_redirect_dns(dns_addr)

    def nixos_restore_dns(self) -> None:
        """Sistem DNS'ini varsayılana döndür."""
        self._do_restore_dns()

    # ── internal helpers ──────────────────────────────────────

    def _find_config(self) -> str:
        for path in _CONFIG_PATHS:
            if os.path.exists(path):
                return path
        # Yoksa yenisini oluştur
        default_path = "/etc/loki/lokinet.ini"
        os.makedirs(os.path.dirname(default_path), exist_ok=True)
        with open(default_path, "w") as f:
            f.write("# lokinet config — generated by entropy-shield\n")
        return default_path

    def _strip_block(self, content: str) -> str:
        """Önceki entropy-shield bloğunu içerikten temizle."""
        lines  = content.splitlines(keepends=True)
        out    = []
        inside = False
        for line in lines:
            if line.strip() == _MARKER_BEGIN:
                inside = True
                continue
            if line.strip() == _MARKER_END:
                inside = False
                continue
            if not inside:
                out.append(line)
        return "".join(out)

    def _service_active(self, name: str) -> bool:
        r = subprocess.run(
            ["systemctl", "is-active", name],
            capture_output=True, text=True,
        )
        return r.stdout.strip() == "active"

    def _wait_active(self, name: str, timeout: int = 20) -> None:
        for _ in range(timeout):
            if self._service_active(name):
                return
            time.sleep(1)
        raise RuntimeError(f"{name} did not become active within {timeout}s.")

    # systemd-resolved üzerinden DNS yönlendirme (Tor'daki ile aynı pattern)

    _DROPIN_DIR  = "/run/systemd/resolved.conf.d"
    _DROPIN_FILE = "/run/systemd/resolved.conf.d/entropy-shield-lokinet.conf"

    def _resolved_running(self) -> bool:
        r = subprocess.run(
            ["systemctl", "is-active", "systemd-resolved"],
            capture_output=True, text=True,
        )
        return r.stdout.strip() == "active"

    def _nixos_ifaces(self) -> list[str]:
        r = subprocess.run(
            ["ip", "-o", "link", "show", "up"],
            capture_output=True, text=True,
        )
        ifaces = []
        for line in r.stdout.splitlines():
            parts = line.split(":")
            if len(parts) >= 2:
                iface = parts[1].strip().split("@")[0].strip()
                if iface and iface not in ("lo", "lokitun0"):
                    ifaces.append(iface)
        return ifaces

    def _do_redirect_dns(self, dns_addr: str) -> None:
        if not self._resolved_running():
            self._log(
                f"[LOKINET] systemd-resolved not active — "
                f"nftables handles DNS redirect to {dns_addr}."
            )
            return

        os.makedirs(self._DROPIN_DIR, exist_ok=True)
        with open(self._DROPIN_FILE, "w") as f:
            f.write("[Resolve]\n")
            f.write(f"DNS={dns_addr}\n")
            f.write("Domains=~.\n")

        for iface in self._nixos_ifaces():
            subprocess.run(
                ["resolvectl", "dns", iface, dns_addr],
                capture_output=True,
            )
            subprocess.run(
                ["resolvectl", "domain", iface, "~."],
                capture_output=True,
            )

        subprocess.run(
            ["systemctl", "reload", "systemd-resolved"],
            capture_output=True,
        )
        self._log(f"[LOKINET] System DNS → Lokinet resolver ({dns_addr}).")

    def _do_restore_dns(self) -> None:
        if not self._resolved_running():
            return
        if os.path.exists(self._DROPIN_FILE):
            os.unlink(self._DROPIN_FILE)
        for iface in self._nixos_ifaces():
            subprocess.run(["resolvectl", "revert", iface], capture_output=True)
        subprocess.run(
            ["systemctl", "reload", "systemd-resolved"],
            capture_output=True,
        )
        self._log("[LOKINET] DNS settings reverted to system defaults.")
